/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Toshiba R734
 */
public class uts extends javax.swing.JFrame {

    /**
     * Creates new form uts
     */
    DefaultTableModel model;
    private Object KoneksiDatabase;
    public uts() throws SQLException {
        setTitle("Perpustakaan");
        initComponents();
        String [] Judul ={"No Peminjaman","Tanggal Pinjam","Nama","Program Studi","Tingkat","Kode Buku","Judul Buku",
        "Penerbit","Penulis","Jumlah Buku"};
        model =new DefaultTableModel(Judul,0);
        jtabel.setModel(model);
        tampilkan();
        
        cboProdi.removeAllItems();
        cboProdi.addItem("Pilih");
        cboProdi.addItem("Sistem Informasi");
        cboProdi.addItem("Pendidikan Fisika");
        cboProdi.addItem("Pendidikan Matematika");
        cboProdi.addItem("Pendidikan Indonesia"); 
        cboProdi.addItem("Pendidikan B.Inggris");
        cboProdi.addItem("Pendidikan Teknologi Informasi");
        cboProdi.addItem("Pendidikan Kewarganegaraan");
        cboProdi.addItem("Pendidikan Biologi");
        cboProdi.addItem("Pendidikan Guru Sekolah Dasar");
        cboTingkat.removeAllItems();
        cboTingkat.addItem("Pilih");
        cboTingkat.addItem("1(Satu)");
        cboTingkat.addItem("2(dua)");
        cboTingkat.addItem("3(Tiga)");
        cboTingkat.addItem("4(Empat)");
        cboJumlahP.removeAllItems();
        cboJumlahP.addItem("Pilih");
        cboJumlahP.addItem("1(Satu)");
        cboJumlahP.addItem("2(dua)");
        cboJumlahP.addItem("3(tiga)");
    }
    private void kosongkan(){
        txtNoP.setText("");
        txtTanggalP.setText("");
        txtNama.setText("");
        cboProdi.setSelectedIndex(0);
        cboTingkat.setSelectedIndex(0);
        txtKodeB.setText("");
        txtJudulB.setText("");
        txtPenerbit.setText("");
        txtPenulis.setText("");
        cboJumlahP.setSelectedIndex(0);
    }
    private Statement st;
    private Connection cn;
    private String sql="";
    private ResultSet rs;
    String nopem;
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNoP = new javax.swing.JTextField();
        txtTanggalP = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboProdi = new javax.swing.JComboBox<>();
        cboTingkat = new javax.swing.JComboBox<>();
        txtKodeB = new javax.swing.JTextField();
        txtJudulB = new javax.swing.JTextField();
        txtPenerbit = new javax.swing.JTextField();
        txtPenulis = new javax.swing.JTextField();
        cboJumlahP = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabel = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PERPUSTAKAAN DITA NURUL RAMADHAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("DATA PEMINJAMAN BUKU");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 23));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Toshiba R734\\Downloads\\books_97178.png")); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Toshiba R734\\Downloads\\books_97178.png")); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No Peminjaman:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 22, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Pinjam:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 68, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nama:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Program Studi:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 164, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tingkat:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 204, -1, -1));

        txtNoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoPActionPerformed(evt);
            }
        });
        jPanel2.add(txtNoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 19, 143, -1));
        jPanel2.add(txtTanggalP, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 65, 143, -1));
        jPanel2.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 117, 143, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kode Buku:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 22, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Judul Buku:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 68, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Penerbit:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Penulis:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 164, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Jumlah Pinjam:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 204, -1, -1));

        cboProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProdiActionPerformed(evt);
            }
        });
        jPanel2.add(cboProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 155, 143, -1));

        cboTingkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboTingkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 199, 143, -1));

        txtKodeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeBActionPerformed(evt);
            }
        });
        jPanel2.add(txtKodeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 19, 174, -1));
        jPanel2.add(txtJudulB, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 65, 174, -1));

        txtPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenerbitActionPerformed(evt);
            }
        });
        jPanel2.add(txtPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 117, 174, -1));

        txtPenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenulisActionPerformed(evt);
            }
        });
        jPanel2.add(txtPenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 161, 174, -1));

        cboJumlahP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboJumlahP, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 199, 174, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 204));

        jTextArea1.setBackground(new java.awt.Color(255, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Catatan:\n1.Tidak boleh meminjam buku lebih dari 3.\n2.Pengembalian buku harus dalam keadaan yang sama.\n3.Batas pinjam yaitu 7 hari,jika terlambat akan terkena denda.\n*telat satu minggu denda Rp.3500*");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 530, 100));

        jtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Peminjaman", "Tanggal Pinjam", "Nama", "Program studi", "Tingkat", "Kode Buku", "Judul Buku", "Penerbit", "Penulis", "Jumlah buku"
            }
        ));
        jtabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtabel);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, -1));

        btnEdit.setText("Edit");
        btnEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, -1));

        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel4.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, -1));

        btnHapus.setText("Hapus");
        btnHapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel4.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, -1));

        btnReset.setText("Reset");
        btnReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 70, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("cari data:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, 10));
        jPanel4.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, -1));

        btnCari.setText("Cari Data");
        btnCari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel4.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 60, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoPActionPerformed

    private void txtKodeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeBActionPerformed

    private void txtPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenerbitActionPerformed

    private void txtPenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenulisActionPerformed

    private void cboProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProdiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboProdiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new terimakasih().setVisible(true);
        
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ditaa","root","");
            String sql="update perpustakaan set TanggalPinjam='"+txtTanggalP.getText()+
                    "',Nama='"+txtNama.getText()+
                    "',ProgramStudi='"+cboProdi.getSelectedItem()+
                    "',Tingkat='"+cboTingkat.getSelectedIndex()+
                    "',KodeBuku='"+txtKodeB.getText()+
                    "',JudulBuku='"+txtJudulB.getText()+
                    "',Penerbit='"+txtPenerbit.getText()+
                    "',Penulis='"+txtPenulis.getText()+
                    "',JumlahBuku='"+cboJumlahP.getSelectedIndex()+
                    "'where NoPeminjaman='"+txtNoP.getText()+"'";
            java.sql.PreparedStatement pst =cn.prepareStatement(sql);
            pst.executeUpdate();
            tampilkan();
            tampil_data();
            reset();
            JOptionPane.showMessageDialog(null, "Berhasil diedit");
        } catch (SQLException ex) {
            Logger.getLogger(uts.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ditaa","root","");
            cn.createStatement().executeUpdate("insert into perpustakaan values"+"('"+txtNoP.getText()+"','"+txtTanggalP.getText()+"','"+txtNama.getText()+"','"+cboProdi.getSelectedItem()+"','"+
                    cboTingkat.getSelectedIndex()+"','"+txtKodeB.getText()+"','"+txtJudulB.getText()+"','"+txtPenerbit.getText()+"','"+txtPenulis.getText()+"','"+cboJumlahP.getSelectedIndex()+"')");
            tampilkan();
            reset();
            JOptionPane.showMessageDialog(null, "Berhasil Disimpan!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ada yang belum diisi!!!");
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ditaa","root","");
            String sql="delete from perpustakaan where NoPeminjaman='"+txtNoP.getText()+"'";
            java.sql.PreparedStatement pst =cn.prepareStatement(sql);
            pst.executeUpdate();
            tampilkan();
            tampil_data();
            reset();
            JOptionPane.showMessageDialog(null, "Berhasil dihapus");
        } catch (SQLException ex) {
            Logger.getLogger(uts.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void jtabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtabelMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ditaa","root","");
            String sql= "select * from perpustakaan where Nama='"+txtCari.getText()+"'";
            java.sql.PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            if(rs.next()){
            txtNoP.setText(rs.getString(1));
            txtTanggalP.setText(rs.getString(2));
            txtNama.setText(rs.getString(3));
            cboProdi.setSelectedItem(rs.getString(4));
            cboTingkat.setSelectedIndex(rs.getInt(5));
            txtKodeB.setText(rs.getString(6));
            txtJudulB.setText(rs.getString(7));
            txtPenerbit.setText(rs.getString(8));
            txtPenulis.setText(rs.getString(9));
            cboJumlahP.setSelectedIndex(rs.getInt(10));
            JOptionPane.showMessageDialog(null, "Data"+"'"+txtCari.getText()+"'"+"ditemukan");
            }
            else{
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        } catch (SQLException ex) {
            Logger.getLogger(uts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new uts().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(uts.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cboJumlahP;
    private javax.swing.JComboBox<String> cboProdi;
    private javax.swing.JComboBox<String> cboTingkat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable jtabel;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJudulB;
    private javax.swing.JTextField txtKodeB;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoP;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPenulis;
    private javax.swing.JTextField txtTanggalP;
    // End of variables declaration//GEN-END:variables

    private void tampilkan(){
       int row = jtabel.getRowCount();
       for (int a= 0; a<row;a++){
           model.removeRow(0);
       }
       try{
           Connection cn =DriverManager.getConnection("jdbc:mysql://localhost:3306/ditaa","root","");
           ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM perpustakaan");
           while(rs.next()){
               String data[]= {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),
               rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)};
               model.addRow(data);
            System.out.println("koneksi berhasil");
            
           }
       }catch (SQLException e){
           System.out.println("gagal koneksi"+e);
       }
    }

    private void tampil_data() {
        DefaultTableModel tabel= new DefaultTableModel();
        tabel.addColumn("NoPeminjaman");
        tabel.addColumn("TanggalPinjam");
        tabel.addColumn("Nama");
        tabel.addColumn("ProgramStudi");
        tabel.addColumn("Tingkat");
        tabel.addColumn("KodeBuku");
        tabel.addColumn("JudulBuku");
        tabel.addColumn("Penerbit");
        tabel.addColumn("penulis");
        tabel.addColumn("JumlahBuku");
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ditaa","root","");
            String sql= "select * from perpustakaan";
            java.sql.PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            while(rs.next()){
                tabel.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getInt(5),
                    rs.getString(16),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getInt(10)});
            }
            jtabel.setModel(tabel);
        } catch (SQLException ex) {
            
        }
        
    }
    private void reset(){
        txtNoP.setText("");
        txtTanggalP.setText("");
        txtNama.setText("");
        cboProdi.setSelectedItem(null);
        cboTingkat.setSelectedIndex(0);
        txtKodeB.setText("");
        txtJudulB.setText("");
        txtPenerbit.setText("");
        txtPenulis.setText("");
        cboJumlahP.setSelectedIndex(0);
    }
    
}

   
